import { describe, it, expect } from "vitest";
import path from "node:path";
import { assembleFromManifest } from "../src/build/assembler.js";

const SOURCES_DIR = path.resolve("sources");
const FIXED_TIMESTAMP = "2026-04-28T00:00:00.000Z";

function buildSkill(skillName: string): string {
  const manifestPath = path.resolve(
    SOURCES_DIR,
    `skills/${skillName}/manifest.yaml`,
  );
  return assembleFromManifest(manifestPath, {
    sourcesDir: SOURCES_DIR,
    timestamp: FIXED_TIMESTAMP,
  });
}

describe("assembler", () => {
  it("starts with frontmatter (no generated header)", () => {
    const output = buildSkill("mvt-analyze");
    expect(output.startsWith("---\n")).toBe(true);
    expect(output).not.toContain("GENERATED by mvtt");
  });

  it("generates valid frontmatter", () => {
    const output = buildSkill("mvt-analyze");
    expect(output).toContain("---\nname: 'mvt-analyze'");
    expect(output).toContain("description:");
  });

  describe("mvt-analyze", () => {
    it("includes Purpose section", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("# MVT Analyze");
      expect(output).toContain("## Purpose");
    });

    it("includes Role section with correct role", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain(
        "You are the **Analyst** -- a Requirements Analysis Expert.",
      );
    });

    it("includes Decision Rules", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("### Decision Rules");
      expect(output).toContain("Clear requirements -> Proceed with structured analysis");
    });

    it("includes Boundaries", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("### Boundaries");
      expect(output).toContain(
        "Do NOT make architecture decisions (use `/mvt-design` instead)",
      );
    });

    it("includes Activation Protocol (Load / Resolve two-block structure, ADR-8)", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Activation Protocol");
      // ADR-8 condensed the five numbered Stages into two topic blocks:
      // Load (read mechanics) and Resolve (decision logic). Assert the blocks
      // and each load-bearing decision unit still render, not the old Stage labels.
      expect(output).toContain("### Load (do this first)");
      expect(output).toContain("### Resolve");
      expect(output).toContain("**Wave 1");
      expect(output).toContain("**Project Scope (PS)**");
      expect(output).toContain("**Knowledge**");
      expect(output).toContain("**Config**");
      // mvt-analyze is a preflight skill, so the Pre-flight unit must render.
      expect(output).toContain("**Pre-flight**");
    });

    it("includes Execution Flow from business.md", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Execution Flow");
      expect(output).toContain("### Step 1: Load Requirements");
      expect(output).toContain("### Step 7: Update Workspace");
    });

    it("includes Artifact Structure section", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Artifact Structure");
      expect(output).toContain("analyze-output.md");
    });

    it("includes Suggested Next Steps", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Suggested Next Steps");
      expect(output).toContain("mvt-analyze");
    });
  });

  describe("mvt-design", () => {
    it("includes correct role", () => {
      const output = buildSkill("mvt-design");
      expect(output).toContain(
        "You are the **Architect** -- a System Architecture Expert.",
      );
    });

    it("includes Variants section", () => {
      const output = buildSkill("mvt-design");
      expect(output).toContain("## Variants");
      expect(output).toContain("/mvt-design --plan");
    });

    it("includes BLOCK-level pre-flight checks", () => {
      const output = buildSkill("mvt-design");
      expect(output).toMatch(/\|\s*\d+\s*\|\s*`[^`]+ is empty`\s*\|\s*BLOCK\s*\|/);
    });
  });

  describe("mvt-fix (shortcut)", () => {
    it("includes Operation Mode: Shortcut section", () => {
      const output = buildSkill("mvt-fix");
      expect(output).toContain("## Operation Mode: Shortcut");
      expect(output).toContain("Do NOT update `active_change`");
    });

    it("has WARN not BLOCK pre-flight", () => {
      const output = buildSkill("mvt-fix");
      expect(output).toMatch(/\|\s*1\s*\|\s*`session\.initialized_at is empty`\s*\|\s*WARN\s*\|/);
      expect(output).not.toMatch(/\|\s*\d+\s*\|\s*`[^`]+ is empty`\s*\|\s*BLOCK\s*\|/);
    });
  });

  describe("mvt-init", () => {
    it("includes Variants", () => {
      const output = buildSkill("mvt-init");
      expect(output).toContain("## Variants");
      expect(output).toContain("interactive refresh");
    });

    it("suggests mvt-analyze as next step", () => {
      const output = buildSkill("mvt-init");
      expect(output).toContain("/mvt-analyze");
    });
  });

  describe("mvt-implement", () => {
    it("includes correct role", () => {
      const output = buildSkill("mvt-implement");
      expect(output).toContain(
        "You are the **Developer** -- an Implementation Specialist.",
      );
    });

    it("session-update section uses script call", () => {
      const output = buildSkill("mvt-implement");
      expect(output).toContain("session-update.cjs");
      expect(output).toContain("--skill mvt-implement");
      expect(output).toContain("Critical flag semantics");
      expect(output).not.toContain("Argument values");
      expect(output).not.toContain(".ai-agents/scripts/session-update.md");
    });

    it("documents silent implement mode across confirmation points", () => {
      const output = buildSkill("mvt-implement");
      expect(output).toContain("preferences.silent.implement");
      expect(output).toContain("skip the preview confirmation");
      expect(output).toContain("skip the scope confirmation");
      expect(output).toContain("skip the deliverables prompt");
      expect(output).toContain("conversation notes");
      expect(output).toContain("generate deliverables when downstream dependents exist");
    });
  });

  describe("mvt-plan-dev", () => {
    it("includes purpose and role", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).toContain("# MVT Plan Dev");
      expect(output).toContain(
        "You are the **Architect** -- a Development Planner.",
      );
    });

    it("does not reference removed plan-dev output template", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).not.toContain(".ai-agents/skills/_templates/plan-dev-output.md");
    });

    it("declares plan-dev specific state updates for active_change and changes", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).toContain("active_change.plan_path");
      expect(output).toContain("changes[]");
    });

    it("includes config-driven granularity guidance", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).toContain("preferences.planning.granularity");
      expect(output).toContain("coarse");
      expect(output).toContain("medium");
      expect(output).toContain("fine");
    });

    it("documents pre-write confirmation and silent plan mode", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).toContain("preferences.silent.plan_dev");
      expect(output).toContain("Confirm and write");
      expect(output).toContain("Revise");
      expect(output).toContain("Cancel");
      expect(output).toContain("do not overwrite");
    });

    it("preflight blocks when active_change is missing", () => {
      const output = buildSkill("mvt-plan-dev");
      expect(output).toContain("active_change.id");
      expect(output).toContain("/mvt-analyze");
    });
  });

  describe("mvt-update-plan", () => {
    it("includes purpose and role", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("# MVT Update Plan");
      expect(output).toContain(
        "You are the **Architect** -- a Development Planner.",
      );
    });

    it("documents soft-prompt natural-language mapping", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("done");
      expect(output).toContain("blocked");
    });

    it("routes an empty plan path instead of blocking it", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("intentional plan-less lifecycle");
      expect(output).not.toContain("No active plan. Run `/mvt-plan-dev` to create one.");
    });

    it("requires re-validation before writing back", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("validate");
      expect(output).toContain("abort");
    });

    it("refreshes changes updated_at", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("changes[]");
      expect(output).toContain("updated_at");
    });
  });

  describe("mvt-resume (Phase 3 enhancements)", () => {
    it("describes multi-plan discovery step", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("### Step 2: Discover Pending Plans");
      expect(output).toContain("artifact-scan.cjs --mode plans");
      expect(output).not.toContain("artifacts/*/plan.yaml");
    });

    it("documents candidate selection branching (0/1/N)", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("### Step 3: Select Target Change");
      expect(output).toContain("Auto-select");
      expect(output).toContain("Pause and prompt");
    });

    it("supports explicit change-id argument", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("{change-id}");
      expect(output).toContain("skip");
    });

    it("includes Plan Progress section in execution flow", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("### Step 6: Load Plan Progress");
      expect(output).toContain("Plan Progress");
      expect(output).toContain("Current Task Detail");
    });

    it("decision rules cover plan-aware branches", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("Multiple in_progress plans found");
      expect(output).toContain("current_task");
      expect(output).toContain("stale warning");
    });

    it("filters skill_history by change_id when plan is selected", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("change_id == selected_change_id");
    });

    it("stale task warning triggers at 5 days", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("5 days");
    });
  });

  describe("mvt-status (Phase 4 multi-change dashboard)", () => {
    it("discovers all plans from scanner output without a fallback glob", () => {
      const output = buildSkill("mvt-status");
      expect(output).toContain("### Step 3: Discover All Plans");
      expect(output).toContain("artifact-scan.cjs --mode plans");
      expect(output).not.toContain("artifacts/*/plan.yaml");
    });

    it("renders Changes Overview table", () => {
      const output = buildSkill("mvt-status");
      expect(output).toContain("Changes Overview");
      expect(output).toContain("change-id");
      expect(output).toContain("progress");
    });

    it("decision rules mention plan-awareness", () => {
      const output = buildSkill("mvt-status");
      expect(output).toContain("Changes Overview table");
      expect(output).toContain("skill_hint");
    });
  });

  describe("mvt-help (Phase 4 diagram update)", () => {
    it("workflow diagram includes plan-dev", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("plan-dev");
      expect(output).toContain("D2[plan-dev]");
    });

    it("references plan-dev in the static skill body (catalog itself is registry-driven at runtime)", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("/mvt-plan-dev");
      expect(output).toContain("registry.yaml");
    });

    it("user position table recommends plan-dev for large changes", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("change is large");
      expect(output).toContain("/mvt-plan-dev");
    });

    it("renders a flat skills catalog instruction without category grouping", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("Display all skills as a single flat table");
      expect(output).toContain("Single flat skills table, sorted by registry declaration order");
      expect(output).not.toContain("Skills tables grouped by category");
      expect(output).not.toContain("section comment headers in `registry.yaml`");
    });

    it("defines evidence and runtime recommendation reuse", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("**Evidence conventions**");
      expect(output).toContain("`.ai-agents/workspace/artifacts/{active_change.id}/`");
      expect(output).toContain("primary runtime recommendation");
      expect(output).toContain("Use that same recommendation in Current Status");
    });

    it("documents mermaid styling and textual fallback status markers", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("classDef done");
      expect(output).toContain("classDef current");
      expect(output).toContain("classDef pending");
      expect(output).toContain("[done]`, `[current]`, or `[pending]");
    });

    it("omits static conditional suggestions so runtime state drives next steps", () => {
      const output = buildSkill("mvt-help");
      expect(output).toContain("### Resolution order");
      expect(output).toContain("Skill names and `description` fields in `registry.yaml`");
      expect(output).not.toContain("`category` and `description`");
      expect(output).not.toContain("### Conditional Recommendations");
      expect(output).not.toContain("active change in progress");
    });
  });

  describe("script-callability sections (change 20260619)", () => {
    it("mvt-update-plan keeps generic plan guidance and inline epic-mode guidance", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("## Script Usage Rule");
      expect(output).toContain("plan-update.cjs");
      expect(output).toContain("--plan");
      expect(output).toContain("--task");
      expect(output).toContain("epic-update.cjs");
      expect(output).toContain("--complete-child");
      expect(output).toContain(".ai-agents/scripts/plan-update.md");
      expect(output).not.toContain(".ai-agents/scripts/epic-update.md");
      expect(output).toContain("exact `epic-update.cjs` mode commands rendered in this skill's workflow");
      expect(output).not.toContain("--child-title");
      expect(output).not.toContain("--child-scope");
      expect(output).not.toContain("--child-depends-on");
    });

    it("mvt-implement omits Script Usage Rule while keeping authoritative deliverables command", () => {
      const output = buildSkill("mvt-implement");
      expect(output).not.toContain("## Script Usage Rule");
      expect(output).toContain("plan-update.cjs");
      expect(output).toContain("Use this exact metadata-only command");
      expect(output).toContain("Do NOT add `--status`");
      expect(output).not.toContain("--status <new_status>");
      expect(output).not.toContain(".ai-agents/scripts/plan-update.md");
      expect(output).not.toContain("epic-update.cjs");
      expect(output).not.toContain(".ai-agents/scripts/epic-update.md");
    });

    it("mvt-decompose omits Script Usage Rule while keeping rendered epic commands", () => {
      const output = buildSkill("mvt-decompose");
      expect(output).not.toContain("## Script Usage Rule");
      expect(output).toContain("epic-update.cjs");
      expect(output).toContain("--validate");
      expect(output).toContain("--add-child");
      expect(output).toContain("--complete-child");
      expect(output).toContain("Do NOT hand-edit `epic.yaml`");
      expect(output).not.toContain("plan-update.cjs");
      expect(output).not.toContain(".ai-agents/scripts/plan-update.md");
    });

    it("mvt-analyze omits Script Usage Rule while keeping epic switch guidance", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).not.toContain("## Script Usage Rule");
      expect(output).toContain("epic-update.cjs");
      expect(output).toContain("--switch-active");
      expect(output).toContain("Do NOT hand-edit `epic.yaml`");
      expect(output).not.toContain("plan-update.cjs");
    });

    it("renders neutral epic requirement context capture and restoration contracts", () => {
      const decompose = buildSkill("mvt-decompose");
      expect(decompose).toContain("requirement-source.cjs --fingerprint");
      expect(decompose).toContain("requirement_context:");
      expect(decompose).toContain("context_refs:");
      expect(decompose).toContain("`epic.yaml` is authoritative");

      for (const skill of ["mvt-analyze", "mvt-resume"]) {
        const output = buildSkill(skill);
        expect(output).toContain(
          "requirement-source.cjs --effective-context <epic_path> --child <change_id>",
        );
        expect(output).toContain("`child`, `context`, `sources`, and `warnings`");
        expect(output).toContain("child.scope");
      }

      for (const skill of [decompose, buildSkill("mvt-analyze"), buildSkill("mvt-resume")]) {
        expect(skill).not.toMatch(/\b(?:v1|v2|legacy)\b/i);
      }
    });

    it("mvt-sync-context omits Script Usage Rule while keeping project plan reminder", () => {
      const output = buildSkill("mvt-sync-context");
      expect(output).not.toContain("## Script Usage Rule");
      expect(output).toContain("plan-update.cjs");
      expect(output).toContain("pass `--projects`");
      expect(output).toContain("Do NOT hand-edit `plan.yaml`");
      expect(output).not.toContain("--status <new_status>");
      expect(output).not.toContain("epic-update.cjs");
    });

    it("mvt-cleanup omits session-only Script Usage Rule", () => {
      const output = buildSkill("mvt-cleanup");
      expect(output).toContain("session-update.cjs");
      expect(output).not.toContain("--close-change");
      expect(output).toContain("--truncate-history");
      expect(output).not.toContain("## Script Usage Rule");
      expect(output).not.toContain("plan-update.cjs");
      expect(output).not.toContain("epic-update.cjs");
    });

    it("script-usage skills still prohibit reading script source files", () => {
      for (const skill of ["mvt-update-plan", "mvt-implement", "mvt-decompose", "mvt-analyze", "mvt-sync-context"]) {
        const output = buildSkill(skill);
        expect(output).toMatch(/Do NOT [^\n]*(?:hand-edit|read `\.cjs`\/`\.js` source|read `\.cjs` or `\.js` source)/);
      }
    });
  });

  describe("lifecycle routing and scanner discovery (change 20260804)", () => {
    it("mvt-update-plan renders finalize, defer, abandon, and recovery routes", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("### Step 5: Lifecycle Routing");
      expect(output).toContain("Complete and defer next");
      expect(output).toContain("--defer-next");
      expect(output).toContain("--abandon-child");
      expect(output).toContain("--abandon-change");
      expect(output).toContain("--close-epic");
      expect(output).toContain("Repair plan");
      expect(output).toContain("Never use `--set-child-status`");
      expect(output).not.toContain("--set-child-status <active_change.id>");
      expect(output).not.toMatch(/epic-update\.cjs[^\n]*--set-child-status/);
      expect(output.indexOf("### Step 1: Classify the Lifecycle Route"))
        .toBeLessThan(output.indexOf("### Step 2: Resolve Task Update"));
    });

    it("mvt-update-plan exposes abandonment for an in-progress change", () => {
      const output = buildSkill("mvt-update-plan");
      const inProgressStart = output.indexOf("#### In-progress plan remains open");
      const recoveryStart = output.indexOf("#### Missing or invalid non-empty plan path");
      const inProgressRoute = output.slice(inProgressStart, recoveryStart);
      expect(inProgressRoute).toContain("explicit abandonment request");
      expect(inProgressRoute).toContain("Abandon change");
      expect(inProgressRoute).toContain("Abandon and advance");
      expect(inProgressRoute).toContain("--abandon-change");
      expect(inProgressRoute).toContain("--abandon-child");
    });

    it("mvt-update-plan uses a lifecycle-only output when no task changed", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("## Lifecycle Update");
      expect(output).toContain("Never fabricate a task id");
      expect(output).toContain("When Steps 2-4 were skipped");
    });

    it("mvt-update-plan routes keep-open through a single session update", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("Keep open");
      expect(output).toContain("--update-change");
      expect(output).toContain("exactly once");
      expect(output).toContain("<route-selected lifecycle flags>\n```");
    });

    it("mvt-update-plan documents divergence without a compensating write", () => {
      const output = buildSkill("mvt-update-plan");
      expect(output).toContain("report the exact divergence");
      expect(output).toContain("compensating");
    });

    it("mvt-analyze renders the active-change conflict preflight", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Active Change Conflict Preflight");
      expect(output).toContain("Continue current change");
      expect(output).toContain("Finalize current change");
      expect(output).toContain("Abandon current change");
    });

    it("mvt-resume renders deferred epic activation through switch-active", () => {
      const output = buildSkill("mvt-resume");
      expect(output).toContain("**Deferred epic**");
      expect(output).toContain("--switch-active");
      expect(output).toContain("--new-change");
      expect(output).toContain("--epic-id");
      expect(output).toContain("only the confirmed deferred-child route may update");
      expect(output).not.toContain("This skill is read-only and does NOT modify");
    });

    it("mvt-cleanup consumes checker findings before a single repair write", () => {
      const output = buildSkill("mvt-cleanup");
      expect(output).toContain("workspace-state-check.cjs");
      expect(output).toContain("--repair-change-statuses");
      expect(output).toContain("prune-empty-changes");
      expect(output).toContain("manual review");
      expect(output).toContain("<action-selected cleanup flags>");
      expect(output).toContain("<action-selected cleanup flags>\n```");
      expect(output).not.toContain("Walk `.ai-agents/workspace/artifacts/`");
    });

    it("mvt-sync-context and mvt-check-context use scanner-only discovery", () => {
      const sync = buildSkill("mvt-sync-context");
      expect(sync).toContain("artifact-scan.cjs --mode change-dirs");
      expect(sync).not.toContain("Fallback scan");
      expect(sync).not.toContain("artifacts/*/");
      const check = buildSkill("mvt-check-context");
      expect(check).toContain("artifact-scan.cjs --mode files");
    });

    it("no discovery workflow retains a fallback recursive artifact glob", () => {
      for (const skill of ["mvt-status", "mvt-resume", "mvt-sync-context", "mvt-check-context"]) {
        const output = buildSkill(skill);
        expect(output, skill).not.toContain("artifacts/*/plan.yaml");
      }
    });
  });

  describe("turn-boundary-contract (change 20260629)", () => {
    // In-scope = references role-header.md AND can pause for user input.
    // Excluded = pure read-out/utility skills that never wait (status, check-context) or have no role-header (help).
    const IN_SCOPE = [
      "mvt-analyze", "mvt-analyze-code", "mvt-bug-detect", "mvt-cleanup", "mvt-config",
      "mvt-create-skill", "mvt-decompose", "mvt-design", "mvt-fix", "mvt-implement",
      "mvt-init", "mvt-manage-context", "mvt-plan-dev", "mvt-quick-dev", "mvt-refactor",
      "mvt-resume", "mvt-review", "mvt-sync-context", "mvt-template", "mvt-test", "mvt-update-plan",
    ];
    const EXCLUDED = ["mvt-status", "mvt-check-context", "mvt-help"];

    it("renders the contract for every in-scope skill with both rules", () => {
      for (const skill of IN_SCOPE) {
        const output = buildSkill(skill);
        expect(output, skill).toContain("## Turn Boundary Contract (Mandatory for interactive pauses)");
        expect(output, skill).toContain("**Rule 1");
        expect(output, skill).toContain("**Rule 2");
        expect(output, skill).toContain("⟦Role Lock⟧");
      }
    });

    it("substitutes role and this_skill into the role-lock notice", () => {
      const analyze = buildSkill("mvt-analyze");
      expect(analyze).toContain("I remain **Analyst** (`/mvt-analyze`)");
      const decompose = buildSkill("mvt-decompose");
      expect(decompose).toContain("I remain **Strategist** (`/mvt-decompose`)");
    });

    it("references the Boundaries above instead of re-rendering them (no duplication)", () => {
      const output = buildSkill("mvt-analyze");
      // The contract points at the Role section's Boundaries rather than listing Do-NOTs again.
      expect(output).toContain("The Boundaries in my Role section above stay in force");
      // The skill's specific Do-NOT line appears once (from role-header), not a second time inside the contract.
      const occurrences = output.split("Do NOT make architecture decisions").length - 1;
      expect(occurrences).toBe(1);
    });

    it("leaves no unresolved mustache placeholders in any in-scope skill", () => {
      for (const skill of IN_SCOPE) {
        const output = buildSkill(skill);
        expect(output, skill).not.toMatch(/\{\{/);
      }
    });

    it("does not render the contract for excluded skills", () => {
      for (const skill of EXCLUDED) {
        const output = buildSkill(skill);
        expect(output, skill).not.toContain("Turn Boundary Contract");
      }
    });
  });
});
