import { describe, it, expect } from "vitest";
import path from "node:path";
import { assembleFromManifest } from "../src/build/assembler.js";

const SOURCES_DIR = path.resolve("sources");
const FIXED_TIMESTAMP = "2026-04-28T00:00:00.000Z";

function buildSkill(skillName: string): string {
  const manifestPath = path.resolve(
    SOURCES_DIR,
    `skills/${skillName}/manifest.yaml`,
  );
  return assembleFromManifest(manifestPath, {
    sourcesDir: SOURCES_DIR,
    timestamp: FIXED_TIMESTAMP,
  });
}

describe("assembler", () => {
  it("generates GENERATED header", () => {
    const output = buildSkill("mvt-analyze");
    expect(output).toMatch(
      /^<!-- GENERATED by mvtt v2\.0\.0 @ 2026-04-28T00:00:00\.000Z/,
    );
  });

  it("generates valid frontmatter", () => {
    const output = buildSkill("mvt-analyze");
    expect(output).toContain("---\nname: 'mvt-analyze'");
    expect(output).toContain("description:");
  });

  describe("mvt-analyze", () => {
    it("includes Purpose section", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("# MVT Analyze");
      expect(output).toContain("## Purpose");
    });

    it("includes Role section with correct role", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain(
        "You are the **Analyst** -- a Requirements Analysis Expert.",
      );
    });

    it("includes Decision Rules", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("### Decision Rules");
      expect(output).toContain("Clear requirements -> Proceed with structured analysis");
    });

    it("includes Boundaries", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("### Boundaries");
      expect(output).toContain(
        "Do NOT make architecture decisions -> Suggest `/mvt-design`",
      );
    });

    it("includes Activation Protocol", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Activation Protocol");
      expect(output).toContain("### Step 1: Load Context");
      expect(output).toContain("### Step 2: Load Config");
      expect(output).toContain("### Step 3: Pre-flight Checks");
    });

    it("includes extended context", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("Extended context for this skill:");
      expect(output).toContain(".ai-agents/workspace/requirements/");
    });

    it("includes Execution Flow from business.md", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Execution Flow");
      expect(output).toContain("### Step 1: Load Requirements");
      expect(output).toContain("### Step 5: Update Workspace");
    });

    it("includes Output Format section", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Output Format");
      expect(output).toContain("analyze-output.md");
    });

    it("includes Suggested Next Steps", () => {
      const output = buildSkill("mvt-analyze");
      expect(output).toContain("## Suggested Next Steps");
      expect(output).toContain("/mvt-design");
      expect(output).toContain("/mvt-status");
    });
  });

  describe("mvt-design", () => {
    it("includes correct role", () => {
      const output = buildSkill("mvt-design");
      expect(output).toContain(
        "You are the **Architect** -- a System Architecture Expert.",
      );
    });

    it("includes Variants section", () => {
      const output = buildSkill("mvt-design");
      expect(output).toContain("## Variants");
      expect(output).toContain("/mvt-design --plan");
    });

    it("includes BLOCK-level pre-flight checks", () => {
      const output = buildSkill("mvt-design");
      expect(output).toContain("BLOCK");
    });
  });

  describe("mvt-fix (shortcut)", () => {
    it("includes Shortcut Operation Rules", () => {
      const output = buildSkill("mvt-fix");
      expect(output).toContain("### Shortcut Operation Rules");
      expect(output).toContain("Do NOT update `progress`");
    });

    it("has WARN not BLOCK pre-flight", () => {
      const output = buildSkill("mvt-fix");
      expect(output).toContain("WARN");
      expect(output).not.toContain("BLOCK");
    });
  });

  describe("mvt-init", () => {
    it("includes Variants", () => {
      const output = buildSkill("mvt-init");
      expect(output).toContain("## Variants");
      expect(output).toContain("--light");
      expect(output).toContain("--deep");
      expect(output).toContain("--refresh");
    });

    it("suggests mvt-analyze as next step", () => {
      const output = buildSkill("mvt-init");
      expect(output).toContain("/mvt-analyze");
    });
  });

  describe("mvt-implement", () => {
    it("includes correct role", () => {
      const output = buildSkill("mvt-implement");
      expect(output).toContain(
        "You are the **Developer** -- an Implementation Specialist.",
      );
    });

    it("includes coding standards in extended context", () => {
      const output = buildSkill("mvt-implement");
      expect(output).toContain("coding-standards.md");
    });
  });
});
