import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { materializeProject } from "../../src/fs/materialize.js";
import {
  readInstallationManifest,
  writeInstallationManifest,
} from "../../src/fs/install-manifest.js";
import { installCommand } from "../../src/commands/install.js";

const PACKAGE_ROOT = path.resolve(".");

describe("install (via materialize + manifest)", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(path.join(os.tmpdir(), "mvtt-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("creates all generated files", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
    });

    expect(materialized.length).toBeGreaterThan(25);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-analyze/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-init/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/analyze-output.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-plan-dev/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-update-plan/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/project-context.md"))).toBe(true);
  });

  it("creates CREATE_ONCE files", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/config.yaml"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/session.yaml"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/project-context.yaml"))).toBe(true);
  });

  it("creates USER DATA directories", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/artifacts"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/custom"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/knowledge/principle"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/knowledge/project"))).toBe(true);
  });

  it("copies knowledge files", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(
      existsSync(path.join(tmpDir, ".ai-agents/knowledge/core/manifest.yaml")),
    ).toBe(true);
    expect(
      existsSync(path.join(tmpDir, ".ai-agents/knowledge/core/user")),
    ).toBe(true);
  });

  it("copies registry to runtime", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/registry.yaml"))).toBe(true);
  });

  it("generated skill files start with frontmatter", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    const content = readFileSync(
      path.join(tmpDir, ".claude/skills/mvt-analyze/SKILL.md"),
      "utf-8",
    );
    expect(content.startsWith("---\n")).toBe(true);
    expect(content).not.toContain("GENERATED by mvtt");
  });

  it("writes installation manifest", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
    });
    writeInstallationManifest(tmpDir, "2.0.0", materialized, null);
    const manifest = readInstallationManifest(tmpDir);
    expect(manifest).not.toBeNull();
    expect(manifest!.mvtt_version).toBe("2.0.0");
    expect(Object.keys(manifest!.files).length).toBeGreaterThan(25);
  });

  it("installCommand writes language to config.yaml (non-TTY defaults to en-US)", async () => {
    const originalCwd = process.cwd();
    process.chdir(tmpDir);
    try {
      await installCommand();
      const config = readFileSync(path.join(tmpDir, ".ai-agents/config.yaml"), "utf-8");
      expect(config).toMatch(/interaction_language:\s*en-US/);
      expect(config).toMatch(/document_output_language:\s*en-US/);
    } finally {
      process.chdir(originalCwd);
    }
  });
});
