import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import path from "node:path";
import os from "node:os";
import { materializeProject } from "../../src/fs/materialize.js";
import {
  readInstallationManifest,
  writeInstallationManifest,
} from "../../src/fs/install-manifest.js";
import { installCommand } from "../../src/commands/install.js";

vi.mock("@clack/prompts", () => ({
  select: vi.fn().mockResolvedValue("en-US"),
  multiselect: vi.fn().mockResolvedValue(["claude"]),
  confirm: vi.fn().mockResolvedValue(true),
  isCancel: vi.fn().mockReturnValue(false),
  intro: vi.fn(),
  outro: vi.fn(),
  cancel: vi.fn(),
  tasks: vi.fn().mockImplementation(async (taskDefs: Array<{ task: (msg: (s: string) => void) => Promise<string> | string }>) => {
    for (const t of taskDefs) await t.task(() => {});
  }),
  log: {
    info: vi.fn(),
    success: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    message: vi.fn(),
  },
}));

const PACKAGE_ROOT = path.resolve(".");

describe("install (via materialize + manifest)", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(path.join(os.tmpdir(), "mvtt-test-"));
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("creates all generated files", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
    });

    expect(materialized.length).toBeGreaterThan(25);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-analyze/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-init/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/analyze-output.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-plan-dev/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-update-plan/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/project-context.md"))).toBe(true);
  });

  it("creates CREATE_ONCE files", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/config.yaml"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/session.yaml"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/project-context.yaml"))).toBe(true);
  });

  it("creates USER DATA directories", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/workspace/artifacts"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/custom"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/knowledge/principle"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".ai-agents/knowledge/project"))).toBe(true);
  });

  it("copies knowledge files", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(
      existsSync(path.join(tmpDir, ".ai-agents/knowledge/core/manifest.yaml")),
    ).toBe(true);
    expect(
      existsSync(path.join(tmpDir, ".ai-agents/knowledge/core/user")),
    ).toBe(true);
  });

  it("copies registry to runtime", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    expect(existsSync(path.join(tmpDir, ".ai-agents/registry.yaml"))).toBe(true);
  });

  it("generated skill files start with frontmatter", () => {
    materializeProject({ packageRoot: PACKAGE_ROOT, projectRoot: tmpDir });
    const content = readFileSync(
      path.join(tmpDir, ".claude/skills/mvt-analyze/SKILL.md"),
      "utf-8",
    );
    expect(content.startsWith("---\n")).toBe(true);
    expect(content).not.toContain("GENERATED by mvtt");
  });

  it("writes installation manifest", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
    });
    writeInstallationManifest(tmpDir, "2.0.0", materialized, null);
    const manifest = readInstallationManifest(tmpDir);
    expect(manifest).not.toBeNull();
    expect(manifest!.mvtt_version).toBe("2.0.0");
    expect(Object.keys(manifest!.files).length).toBeGreaterThan(25);
  });

  it("installCommand writes language to config.yaml (non-TTY defaults to en-US)", async () => {
    const originalCwd = process.cwd();
    process.chdir(tmpDir);
    try {
      await installCommand();
      const config = readFileSync(path.join(tmpDir, ".ai-agents/config.yaml"), "utf-8");
      expect(config).toMatch(/interaction_language:\s*en-US/);
      expect(config).toMatch(/document_output_language:\s*en-US/);
    } finally {
      process.chdir(originalCwd);
    }
  });

  // -- Multi-platform tests --

  it("multi-platform: writes skill files to all selected platforms", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
      platforms: ["claude", "qoder"],
    });

    // Both platforms should have skill files
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-init/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".qoder/skills/mvt-init/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-analyze/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".qoder/skills/mvt-analyze/SKILL.md"))).toBe(true);

    // Templates should still be in .ai-agents (not per-platform)
    expect(existsSync(path.join(tmpDir, ".ai-agents/skills/_templates/analyze-output.md"))).toBe(true);
  });

  it("multi-platform: content is identical across platforms", () => {
    materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
      platforms: ["claude", "qoder"],
    });

    const claudeContent = readFileSync(
      path.join(tmpDir, ".claude/skills/mvt-init/SKILL.md"),
      "utf-8",
    );
    const qoderContent = readFileSync(
      path.join(tmpDir, ".qoder/skills/mvt-init/SKILL.md"),
      "utf-8",
    );
    expect(qoderContent).toBe(claudeContent);
  });

  it("multi-platform: materialized count includes all platform outputs", () => {
    const singlePlatform = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
      platforms: ["claude"],
    });
    const singleSkillCount = singlePlatform.filter(
      (f) => f.category === "generated" && f.relPath.includes("/skills/mvt-"),
    ).length;

    // Clean tmpDir for second run
    rmSync(tmpDir, { recursive: true, force: true });
    tmpDir = mkdtempSync(path.join(os.tmpdir(), "mvtt-test-"));

    const dualPlatform = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
      platforms: ["claude", "qoder"],
    });
    const dualSkillCount = dualPlatform.filter(
      (f) => f.category === "generated" && f.relPath.includes("/skills/mvt-"),
    ).length;

    expect(dualSkillCount).toBe(singleSkillCount * 2);
  });

  it("default (no platforms param): only writes to .claude (backward compat)", () => {
    const materialized = materializeProject({
      packageRoot: PACKAGE_ROOT,
      projectRoot: tmpDir,
    });

    expect(existsSync(path.join(tmpDir, ".claude/skills/mvt-init/SKILL.md"))).toBe(true);
    expect(existsSync(path.join(tmpDir, ".qoder/skills/mvt-init/SKILL.md"))).toBe(false);

    const skillEntries = materialized.filter(
      (f) => f.category === "generated" && f.relPath.includes("/skills/mvt-"),
    );
    expect(skillEntries.every((f) => f.relPath.startsWith(".claude/skills/"))).toBe(true);
  });
});
