import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";

export interface InstallManifest {
  version: number;
  generated: Array<{ pattern: string; source: string }>;
  create_once: Array<{ path: string; source: string }>;
  user_data_dirs: string[];
}

export function loadInstallManifest(packageRoot: string): InstallManifest {
  const manifestPath = path.resolve(packageRoot, "install-manifest.yaml");
  const raw = readFileSync(manifestPath, "utf-8");
  return parseYaml(raw) as InstallManifest;
}

const GENERATED_MARKER = "<!-- GENERATED by mvtt";

export function isGeneratedFile(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, "utf-8");
  return content.trimStart().startsWith(GENERATED_MARKER);
}
